### ISSUE TITLE
ElvUI_VisualAuraTimers - Backport

### ISSUE THREAD

**Issue by Crumdidlyumshis** [ElvUI-WotLK/ElvUI_Enhanced#10]
Could you possibly backport this addon? http://www.tukui.org/addons/index.php?act=view&id=91

**Comment by Mangos02** [comment]
i would also like this to be added to the project, Please and thank you.

**Comment by Crumdidlyumshis** [comment]
Haha I forgot I had posted this. Guess I need to port it to TBC :P

**Comment by Bunny67** [comment]
We do not know player aura duration in the TBC

**Comment by Crumdidlyumshis** [comment]
If a db was setup to input all the spells and times with those spells then It can be done. :)

**Comment by Bunny67** [comment]
This is not a good solution :)

**Comment by Crumdidlyumshis** [comment]
Any solution? I know it’s possible ;P
