### ISSUE TITLE
Enhanced Character Frame bugged

### ISSUE THREAD

**Issue by Emesh95** [ElvUI-WotLK/ElvUI_Enhanced#102]
Hello, I upgraded to the newest version of ElvUI enhanced from 2018 version (i think it was) and this version is bugged
here is the issue: When i mark up Enhanced Character Frame (i tried all options on and also Enhanced Ch. F. only) it completely delete all stats etc (not showing any stats, item lvl, gs) 

![WoWScrnShot_012120_160721](https://user-images.githubusercontent.com/60144657/72816359-4c254e00-3c68-11ea-96a6-0eb0bdb100f5.jpg)

And here is error message:

Date: 2020-01-21 16:12:38
ID: 1
Error occured in: Global
Count: 1
Message: ...s\ElvUI_Enhanced\Modules\Blizzard\CharacterFrame.lua line 2127:
   attempt to call method 'SetBackdropHitRect' (a nil value)
Debug:
   [string "*:OnLoad"]:6:
      [string "*:OnLoad"]:1
   (tail call): ?
   ...s\ElvUI_Enhanced\Modules\Blizzard\CharacterFrame.lua:2127: Initialize()
   ...s\ElvUI_Enhanced\Modules\Blizzard\CharacterFrame.lua:2786:
      ...s\ElvUI_Enhanced\Modules\Blizzard\CharacterFrame.lua:2785
   ...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:157:
      ...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:157
   [string "safecall Dispatcher[1]"]:4:
      [string "safecall Dispatcher[1]"]:4
   [C]: ?
   [string "safecall Dispatcher[1]"]:13: ?()
   ...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:92: Fire()
   ElvUI\Core\Core.lua:1077: CallLoadedModule()
   ElvUI\Core\Core.lua:1102: InitializeModules()
   ElvUI\Core\Core.lua:1258: Initialize()
   ElvUI\Init.lua:202:
      ElvUI\Init.lua:201
AddOns:
  Swatter, v5.8.4723 (CreepyKangaroo)
  AckisRecipeList, vv2.01-14-gfc58e9f
  Atlas, v1.17.0
  AtlasBattlegrounds, v1.17.0
  AtlasDungeonLocs, v1.17.0
  AtlasOutdoorRaids, v1.17.0
  AtlasTransportation, v1.17.0
  AtlasLoot, vv5.11.04
  AtlasQuest, v4.4.3
  AucAdvanced, v5.8.4723 (CreepyKangaroo)
  AucFilterBasic, v5.8.4723 (CreepyKangaroo)
  AucFilterOutlier, v5.8.4723.2531
  AucMatchUndercut, v5.8.4723.2531
  AucScanData, v5.8.4723 (CreepyKangaroo)
  AucStatHistogram, v5.8.4723 (CreepyKangaroo)
  AucStatiLevel, v5.8.4723 (CreepyKangaroo)
  AucStatPurchased, v5.8.4723 (CreepyKangaroo)
  AucStatSales, v5.8.4723.2842
  AucStatSimple, v5.8.4723 (CreepyKangaroo)
  AucStatStdDev, v5.8.4723 (CreepyKangaroo)
  AucStatWOWEcon, v5.8.4723.2530
  AucUtilAHWindowControl, v5.8.4723.3311
  AucUtilAppraiser, v5.8.4723.2530
  AucUtilAskPrice, v5.8.4723.3175
  AucUtilAutoMagic, v5.8.4723.3142
  AucUtilCompactUI, v5.8.4723.2530
  AucUtilEasyBuyout, v5.8.4723.3583
  AucUtilFixAH, v5.8.4723 (CreepyKangaroo)
  AucUtilGlypher, v5.8.4723.2545
  AucUtilItemSuggest, v5.8.4723.3108
  AucUtilPriceLevel, v5.8.4723.2545
  AucUtilScanButton, v5.8.4723.2530
  AucUtilScanFinish, v5.8.4723.3576
  AucUtilScanProgress, v5.8.4723.2530
  AucUtilScanStart, v5.8.4723.2530
  AucUtilSearchUI, v5.8.4723.3655
  AucUtilSimpleAuction, v5.8.4723.4546
  AucUtilVendMarkup, v5.8.4723.2530
  Auctionator, v2.6.3
  AutoAcceptEnchantReplace, v
  BeanCounter, v5.8.4723 (CreepyKangaroo)
  BonusScanner, v5.3
  Configator, v5.1.DEV.278
  DBMCore, v
  ElvUI, v6.06
  ElvUIAddOnSkins, v1.04
  ElvUIEnhanced, v1.04
  ElvUIEnhancedFriendsList, v1.09
  ElvUILocPlus, v2.25
  ElvUIVisualAuraTimers, v1.51
  ElvUIVisualProcs, v1.03
  FishingBuddy, v0.9.8p1
  Gatherer, v3.1.16
  GearScore, v3.1.17 - Release
  Informant, v5.8.4723 (CreepyKangaroo)
  Omen, v3.0.9
  Spy, v
  Stubby, v5.8.4723 (CreepyKangaroo)
  TradeSkillMaster, vv1.4.3
  TradeSkillMasterAccounting, vv1.1.2
  TradeSkillMasterAdditions, vv2.0.1
  TradeSkillMasterAuctionDB, vv1.3.1
  TradeSkillMasterAuctioning, vv1.2.4
  TradeSkillMasterCrafting, vv1.1.5
  TradeSkillMasterDestroying, vv1.2.4
  TradeSkillMasterItemTracker, vv1.1.4
  TradeSkillMasterMailing, vv1.0.5
  TradeSkillMasterShopping, vv1.3.2
  TradeSkillMasterWarehousing, vv1.4.5.1
  WarmaneAHfix, v1.5
  BlizRuntimeLib_enUS v3.3.5.30300 <logon.warmane.com>
  (ck=92e)

**Comment by Loaal** [comment]
You must update ElvUI to [latest version](https://github.com/ElvUI-WotLK/ElvUI/archive/master.zip)

**Comment by Emesh95** [comment]
I did it. I upgraded it from 5.44 to 6.06

**Comment by Apollyonn** [comment]
Use this for now until the next release. https://github.com/ElvUI-WotLK/ElvUI/archive/cf6a24f3deb46db65b546e2ae5e26ad40a3b9d57.zip

**Comment by Emesh95** [comment]
Tyvm its working now :)
