### ISSUE TITLE
Enhanced Character Frame

### ISSUE THREAD

**Issue by weacomeout** [ElvUI-WotLK/ElvUI_Enhanced#103]
gs: 0
Вкладки уехали. 
Все версии аддонов последние. 
Установлены: elv с его мудулями, омен, рекаунт, дбм и gearscore lite.
![WoWScrnShot_012220_170202](https://user-images.githubusercontent.com/57728292/72901074-210b2f00-3d3a-11ea-9e26-c3159b0d0285.jpg)
![WoWScrnShot_012220_170205](https://user-images.githubusercontent.com/57728292/72901076-21a3c580-3d3a-11ea-9cac-732a7fbdf815.jpg)

**Comment by rokpusnik** [comment]
which version of GearScore Lite did this fix? (does not work for me on 3x04 or 3.1.15)

**Comment by Tiny6** [comment]
didn't fix here either.

**Comment by rokpusnik** [comment]
I have noticed it working after some time, but immediately after logon it says GS: 0 still

**Comment by Zidras** [comment]
Also have this issue

**Comment by Tiny6** [comment]
still not fixed.
![WoWScrnShot_020120_160310](https://user-images.githubusercontent.com/16896017/73589077-74d10180-450c-11ea-9ca7-07e0fda21707.jpg)

**Comment by Loaal** [comment]
@Tiny6 please provide error message

**Comment by Tiny6** [comment]
Message: ...s\ElvUI_Enhanced\Modules\Blizzard\CharacterFrame.lua:2188: Usage: GameTooltip:SetText("text" [, color])
Time: 02/01/20 16:22:18
Count: 1
Stack: [C]: ?
[C]: in function `SetText'
...s\ElvUI_Enhanced\Modules\Blizzard\CharacterFrame.lua:2188: in function <...s\ElvUI_Enhanced\Modules\Blizzard\CharacterFrame.lua:2184>

Locals:

**Comment by Tiny6** [comment]
Message: ...s\ElvUI_Enhanced\Modules\Blizzard\CharacterFrame.lua:819: attempt to index local 'data' (a nil value)
Time: 02/01/20 16:23:46
Count: 1
Stack: (tail call): ?
...s\ElvUI_Enhanced\Modules\Blizzard\CharacterFrame.lua:819: in function `ItemLevel'
...s\ElvUI_Enhanced\Modules\Blizzard\CharacterFrame.lua:184: in function `updateFunc'
...s\ElvUI_Enhanced\Modules\Blizzard\CharacterFrame.lua:1275: in function `PaperDollFrame_UpdateStatCategory'
...s\ElvUI_Enhanced\Modules\Blizzard\CharacterFrame.lua:1321: in function `PaperDollFrame_UpdateStats'
...s\ElvUI_Enhanced\Modules\Blizzard\CharacterFrame.lua:1417: in function `PaperDoll_InitStatCategories'
...s\ElvUI_Enhanced\Modules\Blizzard\CharacterFrame.lua:2523: in function `Initialize'
...s\ElvUI_Enhanced\Modules\Blizzard\CharacterFrame.lua:2803: in function <...s\ElvUI_Enhanced\Modules\Blizzard\CharacterFrame.lua:2802>
...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:155: in function <...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:155>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
Interface\AddOns\ElvUI\Core\Core.lua:1077: in function `CallLoadedModule'
Interface\AddOns\ElvUI\Core\Core.lua:1102: in function `InitializeModules'
Interface\AddOns\ElvUI\Core\Core.lua:1262: in function `Initialize'
Interface\AddOns\ElvUI\Init.lua:206: in function <Interface\AddOns\ElvUI\Init.lua:205>

Locals: No locals to dump

**Comment by Zidras** [comment]
Lua error on startup
```
Message: ...s\ElvUI_Enhanced\Modules\Blizzard\CharacterFrame.lua:819: attempt to index local 'data' (a nil value)
Time: 02/01/20 11:56:19
Count: 1
Stack: (tail call): ?
...s\ElvUI_Enhanced\Modules\Blizzard\CharacterFrame.lua:819: in function `ItemLevel'
...s\ElvUI_Enhanced\Modules\Blizzard\CharacterFrame.lua:184: in function `updateFunc'
...s\ElvUI_Enhanced\Modules\Blizzard\CharacterFrame.lua:1275: in function `PaperDollFrame_UpdateStatCategory'
...s\ElvUI_Enhanced\Modules\Blizzard\CharacterFrame.lua:1321: in function `PaperDollFrame_UpdateStats'
...s\ElvUI_Enhanced\Modules\Blizzard\CharacterFrame.lua:1417: in function `PaperDoll_InitStatCategories'
...s\ElvUI_Enhanced\Modules\Blizzard\CharacterFrame.lua:2523: in function `Initialize'
...s\ElvUI_Enhanced\Modules\Blizzard\CharacterFrame.lua:2803: in function <...s\ElvUI_Enhanced\Modules\Blizzard\CharacterFrame.lua:2802>
...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:155: in function <...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:155>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
Interface\AddOns\ElvUI\Core\Core.lua:1077: in function `CallLoadedModule'
Interface\AddOns\ElvUI\Core\Core.lua:1102: in function `InitializeModules'
Interface\AddOns\ElvUI\Core\Core.lua:1262: in function `Initialize'
Interface\AddOns\ElvUI\Init.lua:206: in function <Interface\AddOns\ElvUI\Init.lua:205>

Locals: No locals to dump
```
