### ISSUE TITLE
Enhanced Character Frame

### ISSUE THREAD

**Issue by weacomeout** [ElvUI-WotLK/ElvUI_Enhanced#106]
Иногда случается так, что при входе в игру, в окне персонажа кнопка для открытия поля со статами указывает вниз, и при нажатии на нее, статов нет. 
![WoWScrnShot_021220_005557](https://user-images.githubusercontent.com/57728292/74589901-a670bf00-501a-11ea-90ed-86ba0420aef9.jpg)

![WoWScrnShot_021220_005604](https://user-images.githubusercontent.com/57728292/74589863-395d2980-501a-11ea-82ee-1ffbf6998bcd.jpg)

![WoWScrnShot_020220_195259](https://user-images.githubusercontent.com/57728292/74589963-357dd700-501b-11ea-90fd-8a0f5a7cf5ad.jpg)

Пишем в чате /rl и все становится на свои места.
Последнии версии Элва и его модулей. Кеш почишен.
Omen, Recount, DBM, GearScoreLite.

**Comment by Loaal** [comment]
Нет сообщения об ошибке?

**Comment by weacomeout** [comment]
Сообщений об ошибке нет.

**Comment by Loaal** [comment]
#108
