### ISSUE TITLE
Map/Minimap size

### ISSUE THREAD

**Issue by nadszeg** [ElvUI-WotLK/ElvUI_Enhanced#14]
Can you add a slider to the minimap options, where I can set custom width or height? So people can make wide minimaps, like in Guild Wars 2 (https://d3b4yo2b5lbfy.cloudfront.net/wp-content/uploads/2015/09/7a914EHUI.jpg). Also, I always have the 'smaller world map' option ticked, but every time I open up the map, I have to click the arrow to make it full size (for the smaller version). When turned off, the world map takes up the whole screen, so it's handy to have it smaller... can you give us an option to make it permanently full size with the smaller option on?

**Comment by Bunny67** [comment]
Unfortunately, the minimap can only have square shapes
