### ISSUE TITLE
Make 'SnowFallKeyPress' and 'SnowFallKeyPress Animations' compatible with ElvUI?

### ISSUE THREAD

**Issue by Slickyy** [ElvUI-WotLK/ElvUI_Enhanced#18]
Is it possible to make the flashing star animation compatible with your ElvUI addon? This includes the SnowFallKeyPress and the SnowFallKeyPress Animation.

Thanks in advance.

**Comment by Slickyy** [comment]
For more information about what I'm referring to, here's a example: 

https://www.youtube.com/watch?v=RYPqDlvC1XM

(look at the hotbar when the person triggers a button)
- -

All credits go to their respected owners.

**Comment by Slickyy** [comment]
Here is the link to the folder of the working SnowFallKeyPress with animation, so you can check out the .lua and .toc codes:

http://www.mediafire.com/file/yaf8v6oed6pbxbr/SnowFallKeyPress.zip

**Comment by Bunny67** [comment]
In my opinion this replaces the animation
https://gyazo.com/a928084440193bf252e18abb50eb3817

**Comment by Bunny67** [comment]
added https://github.com/ElvUI-WotLK/ElvUI_Enhanced/commit/7ef7b5c043988d8484bca1400c85f77ed55556a7
