### ISSUE TITLE
ElvUI Errors...

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-WotLK/ElvUI_Enhanced#24]
**Periodically, there are data errors, is it possible to fix it? Thanks)**

2x AIO_Client\index.lua:23: bad argument #1 to 'find' (string expected, got nil)
AIO_Client\index.lua:23: in function `Find'
AIO_Client\index.lua:17: in function `Scan'
AIO_Client\index.lua:39: in function <AIO_Client\index.lua:37>
ElvUI-5.36\modules\bags\bags.lua:274: in function `UpdateSlot'
ElvUI-5.36\modules\bags\bags.lua:713: in function <ElvUI\modules\bags\bags.lua:707>
<in C code>: ?
ElvUI-5.36\modules\bags\sort.lua:335: in function `PickupItem'
ElvUI-5.36\modules\bags\sort.lua:717: in function `DoMove'
ElvUI-5.36\modules\bags\sort.lua:801: in function `DoMoves'
ElvUI-5.36\modules\bags\sort.lua:130: in function <ElvUI\modules\bags\sort.lua:126>

Locals:
text = nil

  **---**

12x AIO_Client\index.lua:23: bad argument #1 to 'find' (string expected, got nil)
AIO_Client\index.lua:23: in function `Find'
AIO_Client\index.lua:17: in function `Scan'
AIO_Client\index.lua:39: in function <AIO_Client\index.lua:37>
ElvUI-5.36\modules\bags\bags.lua:274: in function `UpdateSlot'
ElvUI-5.36\modules\bags\bags.lua:345: in function `UpdateBagSlots'
ElvUI-5.36\modules\bags\bags.lua:731: in function <ElvUI\modules\bags\bags.lua:707>

Locals:
text = nil

  **---**

6x <event>ADDON_ACTION_BLOCKED:AddOn 'ElvUI' tried to call the protected function 'LootSlot()'.
<in C code>: ?
ElvUI-5.36\modules\misc\loot.lua:71: in function <ElvUI\modules\misc\loot.lua:58>

  **---**

1x ElvUI_Enhanced-1.01\Modules\Misc\characterFrame.lua:1829: attempt to index global 'mod' (a function value)
<in C code>: ?

Locals:
(*temporary) = <function> defined =[C]:-1
 = <function> @ Interface\FrameXML\PaperDollFrame.lua:155:
 = <function> @ ElvUI_Enhanced\Modules\Misc\characterFrame.lua:1806:

  **---**

1x AIO_Client\index.lua:23: bad argument #1 to 'find' (string expected, got nil)
AIO_Client\index.lua:23: in function `Find'
AIO_Client\index.lua:17: in function `Scan'
AIO_Client\index.lua:39: in function `GetInventoryItemLink'
LibHealComm-4.0-66:1765: in function `?'
LibHealComm-4.0-66:2745: in function <...ns\oUF_HealComm4\LibHealComm-4.0\LibHealComm-4.0.lua:2744>

Locals:
text = nil

  **---**

3x ElvUI-5.36\modules\bags\bags.lua:193: attempt to index local 'button' (a nil value)
ElvUI-5.36\modules\bags\bags.lua:147: in function <ElvUI\modules\bags\bags.lua:119>

Locals:
self = ElvUI_ContainerFrameEditBox {
 0 = <userdata>
 backdrop = <unnamed> {}
 searchIcon = <unnamed> {}
}
MIN_REPEAT_CHARACTERS = 3
searchString = ""
prevSearchString = ""
SEARCH_STRING = ""
len = <function> defined =[C]:-1
sub = <function> defined =[C]:-1
B = <table> {
 DisableBlizzard = <function> @ ElvUI\modules\bags\bags.lua:100:
 SetDefaultModuleLibraries = <function> @ ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:398:
 UpdateGoldText = <function> @ ElvUI\modules\bags\bags.lua:821:
 EnableModule = <function> @ ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:363:
 modules = <table> {}
 CancelTimer = <function> @ ElvUI\Libraries\AceTimer-3.0\AceTimer-3.0.lua:161:
 IterateEmbeds = <function> @ ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:473:
 BagFrame = ElvUI_ContainerFrame {}
 SecureHook = <function> @ ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:336:
 BagFrames = <table> {}
 db = <table> {}
 ContructContainerFrame = <function> @ ElvUI\modules\bags\bags.lua:902:
 StartStacking = <function> @ ElvUI\modules\bags\sort.lua:661:
 RawHookScript = <function> @ ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:395:
 CanItemGoInBag = <function> @ ElvUI\modules\bags\sort.lua:431:
 Compress = <function> @ ElvUI\modules\bags\sort.lua:450:
 ResetSlotAlphaForBags = <function> @ ElvUI\modules\bags\bags.lua:391:
 baseName = "ElvUI"
 SetDefaultModulePrototype = <function> @ ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:440:
 SortBags = <function> @ ElvUI\modules\bags\sort.lua:631:
 Layout = <function> @ ElvUI\modules\bags\bags.lua:404:
 Encode_BagSlot = <function> @ ElvUI\modules\bags\sort.lua:373:
 defaultModuleState = true
 SetSlotAlphaForBag = <function> @ ElvUI\modules\bags\bags.lua:374:
 GetContainerFrame = <function> @ ElvUI\modules\bags\bags.lua:67:
 ToggleSortButtonState = <function> @ ElvUI\modules\bags\bags.lua:1246:
 ScheduleTimer = <function> @ ElvUI\Libraries\AceTimer-3.0\AceTimer-3.0.lua:108:
 DisableModule = <function> @ ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:381:
 LoadBagBar = <function> @ ElvUI\modules\bags\bagbar.lua:112:
 Tooltip_Hide = <function> @ ElvUI\modules\bags\bags.lua:96:
 DoMoves = <function> @ ElvUI\modules\bags\sort.lua:737:
 DoMove = <function> @ ElvUI\modules\bags\sort.lua:686:
 RegisterMessage = <function> @ BugSack\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:118:
 UnregisterMessage = <function> @ BugSack\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:181:
 OpenBank = <function> @ ElvUI\modules\bags\bags.lua:1279:
 StopStacking = <function> @ ElvUI\modules\bags\sort.lua:675:
 hooks = <table> {}
 GetNumSlots = <function> @ ElvUI\modules\bags\sort.lua:347:
 CommandDecorator = <function> @ ElvUI\modules\bags\sort.lua:834:
 UpdateAllSlots = <function> @ ElvUI\modules\bags\bags.lua:366:
 UpdateSearch = <function> @ ElvUI\modules\bags\bags.lua:119:
 Token_OnEnter = <function> @ ElvUI\modules\bags\bags.lua:810:
 UpdateSlot = <function> @ ElvUI\modules\bags\bags.lua:268:
 SplitItem = <function> @ ElvUI\modules\bags\sort.lua:339:
 SetEnabledState = <function> @ ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:455:
 Hook = <function> @ ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:274:
 enabledState = true
 Sort 
  **---**

26x AIO_Client\index.lua:23: bad argument #1 to 'find' (string expected, got nil)
AIO_Client\index.lua:23: in function `Find'
AIO_Client\index.lua:17: in function `Scan'
AIO_Client\index.lua:39: in function <AIO_Client\index.lua:37>
ElvUI-5.36\modules\bags\bags.lua:646: in function `UpdateKeySlot'
ElvUI-5.36\modules\bags\bags.lua:719: in function <ElvUI\modules\bags\bags.lua:707>

Locals:
text = nil

  **---**

1x AIO_Client\index.lua:23: bad argument #1 to 'find' (string expected, got nil)
AIO_Client\index.lua:23: in function `Find'
AIO_Client\index.lua:17: in function `Scan'
AIO_Client\index.lua:39: in function <AIO_Client\index.lua:37>
ElvUI-5.36\modules\tooltip\tooltip.lua:182: in function `GetItemLvL'
ElvUI-5.36\modules\tooltip\tooltip.lua:250: in function `ShowInspectInfo'
ElvUI-5.36\modules\tooltip\tooltip.lua:348: in function `?'
AceHook-3.0-8 (ElvUI):90: in function <...e\AddOns\ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:87>
(tail call): ?:
QuestHelper-1.4.1\tooltip.lua:371: in function `func'
QuestHelper-1.4.1\manager_event.lua:43: in function <QuestHelper\manager_event.lua:25>
QuestHelper-1.4.1\manager_event.lua:163: in function <QuestHelper\manager_event.lua:163>
<in C code>: in function `SetUnit'
Interface\FrameXML\UnitFrame.lua:146: in function `UnitFrame_UpdateTooltip':
Interface\FrameXML\UnitFrame.lua:133: in function <Interface\FrameXML\UnitFrame.lua:120>:
<in C code>: ?

Locals:
text = nil

  **---**

2x AIO_Client\index.lua:23: bad argument #1 to 'find' (string expected, got nil)
AIO_Client\index.lua:23: in function `Find'
AIO_Client\index.lua:17: in function `Scan'
AIO_Client\index.lua:39: in function <AIO_Client\index.lua:37>
LibRangeCheck-2.0-100098:720: in function `init'
LibRangeCheck-2.0-100098:959: in function `initialOnUpdate'
LibRangeCheck-2.0-100098:1002: in function <...ed\Libraries\LibRangeCheck-2.0\LibRangeCheck-2.0.lua:996>

Locals:
text = nil

  **---**

2x AIO_Client\index.lua:23: bad argument #1 to 'find' (string expected, got nil)
AIO_Client\index.lua:23: in function `Find'
AIO_Client\index.lua:17: in function `Scan'
AIO_Client\index.lua:39: in function <AIO_Client\index.lua:37>
ElvUI-5.36\modules\bags\bags.lua:274: in function `UpdateSlot'
ElvUI-5.36\modules\bags\bags.lua:713: in function <ElvUI\modules\bags\bags.lua:707>
<in C code>: ?
ElvUI-5.36\modules\bags\sort.lua:335: in function `PickupItem'
ElvUI-5.36\modules\bags\sort.lua:721: in function `DoMove'
ElvUI-5.36\modules\bags\sort.lua:801: in function `DoMoves'
ElvUI-5.36\modules\bags\sort.lua:130: in function <ElvUI\modules\bags\sort.lua:126>

Locals:
text = nil

  ---

**Comment by Crumdidlyumshis** [comment]
Looks to me like you have ElvUI placed in your addons folder incorrectly. Make sure when you download and then extract the ElvUI folders, the folders inside the ElvUI-5.36 needs to be placed in your addons folder. That ElvUI-5.36 sholdn't be showing up in your errors within the paths.

**Comment by Vitoshka** [comment]
I have everything posted correctly on separate folders (F:\Games\WoW\Interface\AddOns), errors appear periodically in the game

**Comment by Crumdidlyumshis** [comment]
@Vitoshka Is this issue recurring since the latest updates?

**Comment by Vitoshka** [comment]
@crumdidlyumshis Пока тестирую, полёт нормальный, ошибок пока не наблюдаю, спасибо за проделанную работу с исправлениями.

**Comment by Crumdidlyumshis** [comment]
@Vitoshka 👍🏻 😀
