### ISSUE TITLE
GearScore Issue

### ISSUE THREAD

**Issue by Noob1e** [ElvUI-WotLK/ElvUI_Enhanced#25]
I used to see target gearscore when I inspect them but with the recent updates of Enhanced, I can't see it anymore.

**Comment by Bunny67** [comment]
gearscore not show in inspect frame

**Comment by Noob1e** [comment]
My bad, sorry.

Can you make it work like that?

**Comment by Bunny67** [comment]
I think there is enough information in the tooltip
