### ISSUE TITLE
Issue/Request with ElvUI Chacater Windows/ElvUI_Bunny

### ISSUE THREAD

**Issue by lierox90** [ElvUI-WotLK/ElvUI_Enhanced#26]
Hi, i have recently made a complex upgrade of ElvUI, i have noticed that ElvUI_Bunny addon was removed from repository, I would be grateful if you guys would tell why but thats additional thing.

Main thing is that i still have old version of addon, but combined with new ElvUI produces this error
'''
Message: Interface\AddOns\Gatherer\Swag\LibSwag.lua:407: Usage: GameTooltip:SetText("text" [, color])
Time: 01/30/18 17:10:16
Count: 1
Stack: [C]: ?
[C]: in function `OldGameTooltipSetText'
Interface\AddOns\Gatherer\Swag\LibSwag.lua:407: in function <Interface\AddOns\Gatherer\Swag\LibSwag.lua:403>
[C]: in function `SetText'
...e\AddOns\ElvUI_Bunny\modules\misc\characterFrame.lua:1418: in function <...e\AddOns\ElvUI_Bunny\modules\misc\characterFrame.lua:1413>

Locals: 
'''
And causes state frame to be empty as seen in attached screen:
![image](https://user-images.githubusercontent.com/4543689/35576997-c2ee3ab2-05e0-11e8-898b-b603fbe7c254.png)

The request part:
It would be really nice if you guys would consider adding this MoP-like view for starts with this side panel rather then regular approach with stats below character as seen here
![image](https://user-images.githubusercontent.com/4543689/35577211-44d150f0-05e1-11e8-80d5-66a487bed6e7.png)

**Comment by Crumdidlyumshis** [comment]
ElvUI_Bunny was removed because all of its features and more were merged into ElvUI_Enhanced. Delete ElvUI_Bunny as it has conflict errors.
