### ISSUE TITLE
PaperDoll LUA error

### ISSUE THREAD

**Issue by lierox90** [ElvUI-WotLK/ElvUI_Enhanced#27]
While lvling i received this error:
'''
Message: ...ace\AddOns\ElvUI_Enhanced\Modules\Misc\paperdoll.lua:63: attempt to index field 'ItemLevel' (a nil value)
Time: 01/30/18 17:25:30
Count: 1
Stack: (tail call): ?
...ace\AddOns\ElvUI_Enhanced\Modules\Misc\paperdoll.lua:63: in function `UpdatePaperDoll'
...ace\AddOns\ElvUI_Enhanced\Modules\Misc\paperdoll.lua:147: in function `?'
...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:147: in function <...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:147>
[string "safecall Dispatcher[2]"]:4: in function <[string "safecall Dispatcher[2]"]:4>
[C]: ?
[string "safecall Dispatcher[2]"]:13: in function `?'
...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:92: in function `Fire'
...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: No locals to dump
'''

When it happened there was ongoing roll for green item

**Comment by Crumdidlyumshis** [comment]
This could be due to your last post. https://github.com/ElvUI-WotLK/ElvUI_Enhanced/issues/26

Make sure you have ElvUI_Bunny removed and reply if you have a reoccurring error. Keeping this open until then.

**Comment by Lameoxx** [comment]
1x ElvUI_Enhanced-1.03\Modules\Misc\paperdoll.lua:63: attempt to index local 'frame' (a nil value)
ElvUI_Enhanced-1.03\Modules\Misc\paperdoll.lua:149: in function `?'
CallbackHandler-1.0-6:145: in function <...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
<string>:"safecall Dispatcher[2]":4: in function <[string "safecall Dispatcher[2]"]:4>
<in C code>: ?
<string>:"safecall Dispatcher[2]":13: in function `?'
CallbackHandler-1.0-6:90: in function `Fire'
AceEvent-3.0-4 (ElvUI):120: in function <...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:119>


thats my bugg with the paperdoll

**Comment by Loaal** [comment]
Can't reproduce, probably already fixed. If you see same error again, please open new issue.
