### ISSUE TITLE
Integration - Kind of MSBT

### ISSUE THREAD

**Issue by tjukoela** [ElvUI-WotLK/ElvUI_Enhanced#3]
Hi,

I haven't seen the floating combat log on the screen, maybe I missed something, however does it possible to implement a kind of MikScrollingBattleText ?
THank you

**Comment by Bunny67** [comment]
I don't quite understand what you mean :(

**Comment by tjukoela** [comment]
https://www.youtube.com/watch?v=y3Q8SI0Qnas

to add directly this addon into the Elvui

**Comment by Apollyonn** [comment]
You can enable the default combat floating text from the blizzard settings. 
![combat](https://cloud.githubusercontent.com/assets/19589902/23104439/a1b7a8ca-f6d6-11e6-950d-6631e9590985.jpg)
Is there a problem with MikScrollingBattleText? I mean the addon works perfectly fine, so whats the point to implement it at ElvUI?
In case you don't have the correct version, get this one and you will notice that there are no problems.
https://wow.curseforge.com/projects/mik-scrolling-battle-text/files/422879
