### ISSUE TITLE
Continuously Having Paperdoll LUA errors.

### ISSUE THREAD

**Issue by karserasl** [ElvUI-WotLK/ElvUI_Enhanced#34]
Dunno where the problem is.

I tried on clean client with only elvui and enhanced.

Still having these errors:

> 
> Message: ...ace\AddOns\ElvUI_Enhanced\Modules\Misc\paperdoll.lua:63: attempt to index local 'frame' (a nil value)
> Time: 06/07/18 18:27:28
> Count: 5
> Stack: (tail call): ?
> ...ace\AddOns\ElvUI_Enhanced\Modules\Misc\paperdoll.lua:63: in function `UpdatePaperDoll'
> ...ace\AddOns\ElvUI_Enhanced\Modules\Misc\paperdoll.lua:149: in function `?'
> ...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:147: in function <...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:147>
> [string "safecall Dispatcher[2]"]:4: in function <[string "safecall Dispatcher[2]"]:4>
> [C]: ?
> [string "safecall Dispatcher[2]"]:13: in function `?'
> ...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:92: in function `Fire'
> ...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:119>
> 
> Locals: No locals to dump

More LUA errors:

> Message: ...ace\AddOns\ElvUI_Enhanced\Modules\Misc\paperdoll.lua:63: attempt to index local 'frame' (a nil value)
> Time: 06/08/18 13:53:53
> Count: 34
> Stack: (tail call): ?
> ...ace\AddOns\ElvUI_Enhanced\Modules\Misc\paperdoll.lua:63: in function `UpdatePaperDoll'
> ...ace\AddOns\ElvUI_Enhanced\Modules\Misc\paperdoll.lua:149: in function `?'
> ...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:147: in function <...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:147>
> [string "safecall Dispatcher[2]"]:4: in function <[string "safecall Dispatcher[2]"]:4>
> [C]: ?
> [string "safecall Dispatcher[2]"]:13: in function `?'
> ...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:92: in function `Fire'
> ...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:119>
> 
> Locals: No locals to dump

**Comment by Loaal** [comment]
Duplicate #27
