### ISSUE TITLE
Possibility to add our own font(s)

### ISSUE THREAD

**Issue by tjukoela** [ElvUI-WotLK/ElvUI_Enhanced#4]
Possibility to add our custom font(s) .ttf etc...

**Comment by Apollyonn** [comment]
You can do it manually. Go to "ElvUI\media\fonts" and add your CustomFont.ttf file there, then go to "ElvUI\media" open the sharedmedia file and add a line with path to register your font, like this.
LSM:Register("font", "CustomFont", [[Interface\AddOns\ElvUI\media\fonts\CustomFont.ttf]]);

**Comment by Loaal** [comment]
https://www.youtube.com/watch?v=l6oLHY7BTFA

**Comment by tjukoela** [comment]
Thank you
