### ISSUE TITLE
Need improvement all Cooldown Override

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-WotLK/ElvUI_Enhanced#40]
Make that please the option: to show or not to show fractions of seconds. So that I can choose when the countdown is shown. Example: up to 3 the time count is shown in yellow, and when the count is less than 3 the time count is shown in red and the time is shown without a fraction of seconds

**This option is required for all tabs: Cooldown Override** 

_**Add please also the font size, font type, font scale and timings format (1, 30, 1m, 1.5m, 30m, 1h) in all tabs Cooldown Override**_

https://b.radikal.ru/b03/1806/e3/af2a10f8a9d1.jpg

https://a.radikal.ru/a15/1806/14/4299e9ac16c8.jpg

https://d.radikal.ru/d26/1806/59/72f1f385c5dc.jpg

**_Please make the tabs ([tabs 1-10](https://b.radikal.ru/b43/1807/07/e1b6b198ddce.jpg), [bags](https://b.radikal.ru/b11/1807/b6/d02b1f3366a4.jpg), [unitframes](https://d.radikal.ru/d38/1807/38/a659c580c42a.jpg)) independent of the [general settings.](https://d.radikal.ru/d25/1807/d6/3109fb44b0de.jpg) So that I can turn the settings on and off separately_**

Cделайте пожалуйста опцию: показывать или не показывать доли секунд. Чтобы я мог выбирать когда показывается отсчёт. Пример: до 3 отсчёт времени показывается жёлтым цветом, а когда отсчёт менее 3 отсчёт времени показывается красным цветом и время показывается без доли секунд

**Данная опция необходима для всех вкладок: Cooldown Override**

**_Добавьте пожалуйста также размер шрифта, вид шрифта, масштаб шрифта и формат времени (1, 30, 1m, 1.5m, 30m, 1h) для всех вкладок Cooldown Override_**

https://b.radikal.ru/b03/1806/e3/af2a10f8a9d1.jpg

https://a.radikal.ru/a15/1806/14/4299e9ac16c8.jpg

https://d.radikal.ru/d26/1806/59/72f1f385c5dc.jpg

**_Сделайте пожалуйста вкладки ([вкладки 1-10](https://b.radikal.ru/b43/1807/07/e1b6b198ddce.jpg), [сумок](https://b.radikal.ru/b11/1807/b6/d02b1f3366a4.jpg), [юнитфреймов](https://d.radikal.ru/d38/1807/38/a659c580c42a.jpg)) не зависимыми от [главных настроек](https://d.radikal.ru/d25/1807/d6/3109fb44b0de.jpg). Чтобы я мог включать и выключать настройки Cooldown Override по отдельности_**

Thank you

**Comment by Vitoshka** [comment]
Также периодически когда я нажимаю комбинацию клавиш Альт+таб, а потом возвращаюсь в игру возникает данное отображение цифр: https://d.radikal.ru/d24/1807/e5/759c9cf17529.jpg 
Я уверен что это также взаимосвязано с Cooldown Override.

**Also periodically when I press Alt + Tab, and then I return to the game, this display of numbers appears:** https://d.radikal.ru/d24/1807/e5/759c9cf17529.jpg I am sure that this is also interrelated with Cooldown Override.

**Comment by Loaal** [comment]
Было добавлено в 6.0 ElvUI
