### ISSUE TITLE
Пропала кнопка выслеживания с миникарты

### ISSUE THREAD

**Issue by 7AllenWalker7** [ElvUI-WotLK/ElvUI_Enhanced#46]
Нет кнопки, меню выслеживания вызывается кликом пкм на миникарте, но иконка нужна для отображения текущего выслеживания (полезно для хантов).

**Comment by Bunny67** [comment]
Не могу воспроизвести
![image](https://user-images.githubusercontent.com/5816685/64629083-3d49a780-d3fb-11e9-839a-e98d541a093e.png)

**Comment by Loaal** [comment]
Меню выслеживания  открывается правым кликом по миникарте
