### ISSUE TITLE
Request: Chat bubbles with nameplates

### ISSUE THREAD

**Issue by Zidras** [ElvUI-WotLK/ElvUI_Enhanced#52]
If Friendly Player nameplates are active with chat bubbles enabled, they should appear on top of player.

1. Step 1: Activate friendly nameplates [iterface>Names>Friendly Units or Shift+V]
2. Step 2: Someone type on /s

Since blizzard did not support this until later expansions, is this request even possible?

Edit: not only friendly chat bubbles but all chat bubbles (friendly, enemy, player, npc). They simply don't work with nameplates active!

**Comment by Zidras** [comment]
Just food for thought: Docsnameplates addon has a way to create chat boxes and embed the CHAT_MSG_CHANNEL request (example: https://www.abload.de/img/desc1ogtg.jpg), which leads me to believe that it is possible to come up with a way to make all /say /party appear as a standard chat bubble while having nameplates on.

**Comment by Zidras** [comment]
Can provide Docs. Addon files if needed

**Comment by Bunny67** [comment]
added
