### ISSUE TITLE
Nameplates Friendly Guild/Title

### ISSUE THREAD

**Issue by Zidras** [ElvUI-WotLK/ElvUI_Enhanced#59]
**Description**

Friendly nameplates with optional tags of guild name and title for both players and NPC is a request of a feature that I think has been implemented on retail elvui (can't confirm but check these ElvUI git posts please):
https://git.tukui.org/elvui/elvui/issues/131
https://git.tukui.org/elvui/elvui/issues/1183

**How do you want it to look/work in comparison to how it is now?**

![image](https://user-images.githubusercontent.com/10605951/63285345-65873000-c2ad-11e9-887a-0978cf04bda8.png)

I also leave a different approach from another 3.3.5a nameplate addon (Docsnameplates) that has this feature, should it be helpful to you: 
![image](https://user-images.githubusercontent.com/10605951/63285413-949da180-c2ad-11e9-86a5-82a9f117d51e.png) ![image](https://user-images.githubusercontent.com/10605951/63285668-32916c00-c2ae-11e9-96f3-9117c88bc8b6.png)

**Comment by Bunny67** [comment]
added

**Comment by Zidras** [comment]
@Bunny67 Guild/Title not updating on mouseover. Only when I move the camera away from the unit and recenter camera (like a 360º rotation), or reloading that it updates.
Edit: Targetting and detargetting also seems to trigger the guildname to appear properly

**Comment by Zidras** [comment]
Also, I notice with "Unknown" people, a (random?/last mouseover?) guild name applies to ALL unknowns:
![image](https://user-images.githubusercontent.com/10605951/64281065-3da0f900-cf4a-11e9-82c0-5571fb54c0a8.png)
![image](https://user-images.githubusercontent.com/10605951/64281128-64f7c600-cf4a-11e9-8ecc-111ff716dc5b.png)
