### ISSUE TITLE
Нужно улучшение: Индикаторы Здоровья

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-WotLK/ElvUI_Enhanced#67]
Дабавьте пож. опции отображения **вкл/выкл** отображение [Guild и NPC](https://d.radikal.ru/d00/1908/ab/337ea032ece1.jpg) в: 
а) Столицах, таверне (в общем, где есть значок отдыха) 
б) В бою
в) В группе
г) В рейде
д) В подземельях (5-10-25-40 человек)
Спасибо

**Comment by Bunny67** [comment]
Был создан такой же запрос #69. Этот закрою что бы не было дубликаций.
