### ISSUE TITLE
[Request] Nameplate name replacement for icon (totems)

### ISSUE THREAD

**Issue by Zidras** [ElvUI-WotLK/ElvUI_Enhanced#70]
Main request is to be able to replace totem name (and/or HP totem bar if enabled) with only the totem icon (and optionally HP bar under icon with same width) like so: 

![image](https://user-images.githubusercontent.com/10605951/64083600-fb917080-cd19-11e9-89b3-2738018ebf55.png) ![image](https://user-images.githubusercontent.com/10605951/64083440-1e228a00-cd18-11e9-860e-583c03fc3223.png) 

Idk the best way to implement this, maybe just an option in ENP saying **'Totem icons'** with a checkbox if the player wants to see only totem icons instead of the written name as default. 
Maybe also add tickboxes for BG/Arena only, combat only, always on, hide on combat, etc...

Or maybe to expand functionality, a way to hook icon and/or replace name for icon in Nameplate style filter (might be useful to hook icon to a specific mob, kinda like TidyPlates+TP might appeal to some): 
![image](https://user-images.githubusercontent.com/10605951/64083664-03054980-cd1b-11e9-81d7-cf8c2d347bef.png)
However, I feel like this might require way more coding (more triggers - subtypes of unit types: totems, pets; more actions - hooking and/or replacing icon (path needed?), avoiding collisions with buffs/debuffs)...

**Comment by Bunny67** [comment]
Will be added in ElvUI. Will be available in next release.

**Comment by Zidras** [comment]
Came here just to add this information but you beat me to it. Fantastic job ty
