### ISSUE TITLE
[Bug] Tooltip progress info misalignment + Gearscore

### ISSUE THREAD

**Issue by Zidras** [ElvUI-WotLK/ElvUI_Enhanced#72]
Progress info of enhanced tooltip gets misaligned. Furthermore, it causes Gearscore to get clipped by healthbar. This issue also happened on elvui 5.xx.

- **Reproduce by:** 
Enable progress info and mouseover player in raid instance.
Shift modifier breaks the alignment; if show always, Shift-mouseover and shift key-up misaligns twice; clicking a new modifier snaps progress block back into tooltip. Other modifiers also randomly break the alignment, however I've consistently reproduced the following situations (see imgs below):

Always show [Shift-down]
![image](https://user-images.githubusercontent.com/10605951/65265899-dff3db80-db09-11e9-92d1-f062261fa28b.png)

Always show [Shift-up]
![image](https://user-images.githubusercontent.com/10605951/65266588-3f062000-db0b-11e9-957a-a2e63e5b5e21.png)

Alt&Ctrl (after /reload or assign new modifier and first unit mousever tooltip):
![image](https://user-images.githubusercontent.com/10605951/65267046-2cd8b180-db0c-11e9-92f6-bd8f049d214d.png)

Shift (after /reload or assign new modifier and first unit mousever tooltip):
![image](https://user-images.githubusercontent.com/10605951/65267349-b8524280-db0c-11e9-8ebc-89a3d8e580b9.png)

Gearscore (Any modifier):
![image](https://user-images.githubusercontent.com/10605951/65266709-7bd21700-db0b-11e9-84df-ba9af2bb31b2.png)

Proper (any modifier, outside raid)
![image](https://user-images.githubusercontent.com/10605951/65268691-9b6b3e80-db0f-11e9-9fff-4c62f36ece7a.png)

**Comment by Loaal** [comment]
Should be fixed after ElvUI-WotLK/ElvUI@4f644ea4ced5453854760506a49c4816876cd4f4
Please retest and report back.

**Comment by Zidras** [comment]
Did a quick testing and couldn't reproduce problem anymore. Good work guys 👍
