### ISSUE TITLE
[REQUEST] Looking to have a totem bar along with a stance bar.

### ISSUE THREAD

**Issue by Cajden** [ElvUI-WotLK/ElvUI_Enhanced#79]
Hello

Been trying on my own but cannot manage to find out how to fix it, or rather get it working.
Looking to have a totem bar so I'm able to dismiss totems at the same time as having any or rather all other classfunctions active.
Example being stance bar, which seem to be overriding any other settings.
Base class where I'm playing is set to druid currently which is why other things might not work.

I tried rewriting all the ¨SHAMAN¨ lines to ¨DRUID¨instead but i am not sure what more needs changing?

**Comment by Loaal** [comment]
https://github.com/ElvUI-WotLK/ElvUI/pull/670/files
These changes will allow you to have stance and totem bars at the same time.
Such functionality will not be implemented as a switch in the options, since it requires a large number of changes.
