### ISSUE TITLE
WIM ElvUI skin backport

### ISSUE THREAD

**Issue by silentwinter** [ElvUI-WotLK/ElvUI_Enhanced#8]
Could it be possible to backport this to 3.3.5 ? 

I tried and miserably failed, so I would like to toss it to professionals.

**Comment by silentwinter** [comment]
https://mods.curse.com/addons/wow/wim-elvui-skin#t1:other-downloads

Here is the link to 7.0- version.

**Comment by silentwinter** [comment]
Actually, disregard this. Just changed client number in toc and worked :>. 

Mark it as resolved please!

**Comment by Crumdidlyumshis** [comment]
Which version of WIM are you using? I did what you did, but WIM is still unskinned.

I downloaded this version of WIM: https://www.wowace.com/projects/wim-3/files/439176

**Comment by silentwinter** [comment]
I have the 3.3.5 version, but I tried with 3.3.7, works fine.

/wim -> General -> Display settings -> Window Skin

You should see it under there.

I personally hate 3.3.7 cuz the slash intercept function doesn't work. (Like, if you type /whisper FooBar, it should pop up the whisper window instead of just writing the whisper on original chatbox.)

Pretty annoying as a person who receives quite a lot of whispers.

**Comment by Crumdidlyumshis** [comment]
Thanks man! Got it working 👍 

Close this if needed.
