### ISSUE TITLE
[Request] Profile swap on specialization change

### ISSUE THREAD

**Issue by rokpusnik** [ElvUI-WotLK/ElvUI_Enhanced#82]
as title says, some way of setting it up so that one can use different profiles for different specs

it could be as simple as:
Tickbox for enable/disable
MainSpec: <dropdown menu for picking which profile>
OffSpec: <dropdown menu for picking which profile>

**Comment by Loaal** [comment]
![image](https://user-images.githubusercontent.com/590348/69010004-ce914900-096b-11ea-83e2-b4c053afaf14.png)
