### ISSUE TITLE
Tooltip Progress Info gives non accurate info

### ISSUE THREAD

**Issue by 3majed** [ElvUI-WotLK/ElvUI_Enhanced#84]
![WoWScrnShot_112119_200509](https://user-images.githubusercontent.com/22427035/69360029-da964700-0c9a-11ea-9c2f-6fea3e4ab962.jpg)

As you see in the pic I don't have Togc 25 achievement but in the tooltip it shows I have it. This issue also happen with Icc HC & non HC

**Comment by Loaal** [comment]
These numbers are based on boss kill statistics
![image](https://user-images.githubusercontent.com/590348/69368538-67e19780-0cab-11ea-9f99-146976bb21ce.png)
Apparently, some servers log incorrect information

**Comment by Loaal** [comment]
As an alternative, a new option for checking achievements was added, but it shows the progress of parts of the dungeons (quarters), because we can not get information about the criteria for incomplete achievements for other players.
30531b9061375f7da7e61d9fd3f68f6d5c0262b7
