### ISSUE TITLE
Feature Request - sorting options

### ISSUE THREAD

**Issue by rokpusnik** [ElvUI-WotLK/ElvUI_Enhanced#87]
similar to group and raid frames - enable the minimap buttons to grow, for example, right and then down, as well as right and up or left and up.

Becomes handy if you have several minimap buttons and have them popped out of the minimap as such: 
![image](https://user-images.githubusercontent.com/49006425/63638904-334f4700-c68e-11e9-905a-56c7e9e2a19a.png)

**Comment by Loaal** [comment]
ElvUI_MinimapButtons was merged into ElvUI_Enhanced

![image](https://user-images.githubusercontent.com/590348/69499345-167f1580-0f02-11ea-9151-36cc0b4716f6.png)
