### ISSUE TITLE
Расположение иконок аддонов под миникартой

### ISSUE THREAD

**Issue by MaelKoT** [ElvUI-WotLK/ElvUI_Enhanced#88]
**Description**

Иконки аддонов под миникартой не меняют свое положение при выборе вариантов расположения.

**Version Number**

6.04
![123](https://i.imgur.com/Ff5S0lR.png)

**Comment by Loaal** [comment]
Указанная на скриншоте опция отвечает за направление роста фрейма
Для перемещения фиксатора иконок нужно в опциях нажать на "Toggle Anchors"/"Показать фиксаторы".

Название опции было исправлено в новой версии, но аддон ElvUI_MinimapButtons был поглощен ElvUI_Enhanced

![image](https://user-images.githubusercontent.com/590348/69499438-3400af00-0f03-11ea-89d7-82c26b0d6de0.png)

![image](https://user-images.githubusercontent.com/590348/69499390-ade46880-0f02-11ea-97b3-706f68487ed6.png)
