### ISSUE TITLE
Связь.

### ISSUE THREAD

**Issue by weacomeout** [ElvUI-WotLK/ElvUI_Enhanced#90]
Извини, дружище, но терпению настал конец. Я так давно наблюдаю за твоей деятельностью и нахожу тебя профессионалом. Ты мониторишь форумы на предмет актуальных запросов от игроков, твердо знаешь, что делаешь, и делаешь это. Мой вопрос не связан напрямую с Элвом или его плагинами, но позволь выйти с тобой на связь тет-а-тет, дабы задать его тебе.

**Comment by Bunny67** [comment]
У нас есть дискорд, ты можешь там написать.
