### ISSUE TITLE
[Request] Add convert to raid & ML to raid_control

### ISSUE THREAD

**Issue by Zidras** [ElvUI-WotLK/ElvUI_Enhanced#91]
Request to add the option to convert to raid and (optionally) assign Master Loot in the panel.
Macro used:
>/script ConvertToRaid();
/script SetLootMethod("master", "player")

![image](https://user-images.githubusercontent.com/10605951/69899878-69265a80-1364-11ea-9892-9ba9f88b4399.png)

**Comment by Apollyonn** [comment]
Its very easy to add this but on 3.3.5 you can only convert party to raid and not vice versa, i don't know if we want this.

**Comment by Zidras** [comment]
Hello Apollyonn, thanks for the feedback.
Althought I'm aware of only being able to do this party > raid, I've always found it very cumbersome to have to open Raid menu every single time I wanted to create a raid. My idea was to simplify the raid creating process by saving a few clicks. Just my 2c
