### ISSUE TITLE
[Request] Nameplate style filter - Trigger: Attackable Unit

### ISSUE THREAD

**Issue by Zidras** [ElvUI-WotLK/ElvUI_Enhanced#92]
Is it possible to know from the API if any unit **not targeted nor mouseovered** is attackable?

I was trying to implement a style filter to hide HP bars from neutral/enemy NPC that I can't attack, using action Name Only but couldn't find any unit flag or reaction in the triggers that could help me. 

Here is what I'm trying to achieve (for this example, I had to manually input the name of unit):

Enemy NPC (eg.: Mojodishu):
![image](https://user-images.githubusercontent.com/10605951/69900577-39c81b80-136d-11ea-8ed9-c319c98288c4.png)

Neutral NPC (eg.: Montok Redhands):
![image](https://user-images.githubusercontent.com/10605951/69900615-a3482a00-136d-11ea-8e7e-7ef90f3ff797.png)

**Comment by Loaal** [comment]
This is not possible, because the only way to find out if you can attack npc is to check via [UnitCanAttack ](https://wowwiki.fandom.com/wiki/API_UnitCanAttack)api function, which require unitID.

**Comment by Zidras** [comment]
Thanks @Loaal for the clarification. I was branching out to other solutions in the style filters because I can't figure out why the game's Friendly and Enemy units are different than ElvUI's Friendly and Enemy units.

- Game units:

Friendly **ON**
![image](https://user-images.githubusercontent.com/10605951/69917786-c6ec9c80-1461-11ea-8afe-bebe266ab3ae.png)


Friendly **OFF**
![image](https://user-images.githubusercontent.com/10605951/69917802-f1d6f080-1461-11ea-9c83-4071325c0863.png)
_**All friendly units NPs toggled off**_
- ElvUI units:


Friendly **ON**
![image](https://user-images.githubusercontent.com/10605951/69917856-9ce7aa00-1462-11ea-87e1-d91d6635c370.png)



Friendly **OFF**
![image](https://user-images.githubusercontent.com/10605951/69917854-95c09c00-1462-11ea-8a12-ec192adb7586.png)
_**Only "green" NPs toggled off**_

**Comment by Loaal** [comment]
It looks like these particular NPCs are friendly, that's why blizzard option toggle them.
In the case of ElvUI, iirc, you can check the NPC reaction only by the color of the status bar (but in that exception case that info is wrong).

**Comment by Zidras** [comment]
You mentioned getting NPC reaction by the color of the status bar and that got me investigating in the files of DocsNameplates to see how the author managed to achieve this.

If I'm understanding the logic behind the code, Docs author first assigns reaction and type of unit based on RGB logic:

```
local function reactionAndType( red, green, blue, data )
    if red < .01 and blue < .01 and green > .99 then
        return "FRIENDLY", "NPC" 
    elseif red < .01 and blue > .99 and green < .01 then
        return "FRIENDLY", "PLAYER"
    elseif red > .99 and blue < .01 and green > .99 then
        return "NEUTRAL", "NPC"
    elseif red > .99 and blue < .01 and green < .01 then
        return "HOSTILE", "NPC"
    else
        return "HOSTILE", "PLAYER"
    end
end
```

[ElvUI](https://github.com/ElvUI-WotLK/ElvUI/blob/d9c064d3fd7c7fb2c5887a68a1057870030d5c12/ElvUI/Modules/Nameplates/Nameplates.lua#L388) does the same but saves Yellow (neutral) as ENEMY_NPC:
```
function NP:GetUnitInfo(frame)
	local r, g, b = frame.oldHealthBar:GetStatusBarColor()

	if r < 0.01 then
		if b < 0.01 and g > 0.99 then
			return 5, "FRIENDLY_NPC"
		elseif b > 0.99 and g < 0.01 then
			return 5, "FRIENDLY_PLAYER"
		end
	elseif r > 0.99 then
		if b < 0.01 and g > 0.99 then
			return 4, "ENEMY_NPC"
		elseif b < 0.01 and g < 0.01 then
			return 2, "ENEMY_NPC"
		end
	elseif r > 0.5 and r < 0.6 then
		if g > 0.5 and g < 0.6 and b > 0.5 and b < 0.6 then
			return 1, "ENEMY_NPC"
		end
	end
	return 3, "ENEMY_PLAYER"
end
```
Followed by [HP bar coloring](https://github.com/ElvUI-WotLK/ElvUI/blob/cbfe4fd13add586dc764c7f2204cb2c4952440b7/ElvUI/Modules/Nameplates/Elements/HealthBar.lua#L65) based on the above.

So, with ElvUI, changing Friendly NPC nameplates only affects the green ones.
_______
Then, Docs has this (I think these are the right code lines):
```
data.red, data.green, data.blue = self.children.healthBar:GetStatusBarColor()
    data.reaction, data.type = reactionAndType( data.red, data.green, data.blue, data )
    if not inCombat and isInSanctuary and data.reaction=="HOSTILE" then data.reaction = "FRIENDLY" end
    data.class, data.role = getClassAndRole( data )
    
    if data.reaction=="FRIENDLY" then
        data.layout = "FRIEND"
    elseif data.reaction=="NEUTRAL" then
        if global.agressiveList[data.nameIs] then
            data.layout = "ENEMY"
        else
            data.layout = "FRIEND"
        end
    else
        data.layout = "ENEMY"
    end
```

So the author here adds some logic with NEUTRAL to distinguish the yellows (for example a beast would be FRIENDLY and if attacked it would turn to ENEMY) as well as isInSanctuary which is a very useful option that I couldn't find in the Triggers.

- [x] **Is _isInSanctuary_ possible to implement in style filters?** Maybe in the Instance Type:

![image](https://user-images.githubusercontent.com/10605951/69921015-4d1ada00-1486-11ea-95d6-5e15a9c54940.png)

Let me know your thoughts on this. If I made a mistake on my wall of text, I apologize in advance, I have almost nil experience with lua and addons in general.


Should you need, I leave the relevant DocsNameplates .lua file for your convenience: [update.txt](https://github.com/ElvUI-WotLK/ElvUI_Enhanced/files/3908795/update.txt)

**Comment by Bunny67** [comment]
added "Sanctuary" instance type in nameplates branch
